name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    uses: kvoon3/workflows/.github/workflows/pnpm-release.yml@main
    with:
      publish: vscode
    permissions:
      contents: write
      id-token: write
      actions: write
    secrets:
      VSCE_PAT: ${{secrets.VSCE_PAT}}
      OVSX_PAT: ${{secrets.OVSX_PAT}}
